title          : Your Project Title
description    : This is the description of your project.
language       : python
from           : 'python-notebooks-prod:61'
runtime_config : default
technology     : 2
