title          : "Introduction to DataCamp Projects (python)"
description    : >
  If you've never done a DataCamp project, this is the place to start! 
language       : python
from           : 'python-notebooks-prod:106'
runtime_config : default
state          : development
long_description: |
  This is an introduction to DataCamp projects. A DataCamp project will allow you to practice and 
  apply the skills you've learned in the DataCamp courses. In each project you will carry out an 
  end-to-end analysis, on a real-world task, using real-world tools and workflows. 
  In this gentle introduction to DataCamp projects, we will walk you through the projects
  interface and you will learn how to work with Jupyter notebooks: 
  an open-source web application that is great for interactive data analysis.
technology: 2
instructors:
  - rasmus@datacamp.com
collaborators:
  - ramnath@datacamp.com
  - martijn@datacamp.com
topics:
  - 2
  - 4
  - 12
prerequisites:
  - 735
  - 799
difficulty_level: 1
time_needed: "30 minutes"
illustration: "https://s3.amazonaws.com/assets.datacamp.com/production/project_33/datasets/project_image.png"

